# Site settings
title: Maria Matteo
url: https://github.com/Mariate25/Traducciones
description: "Traducciones de todo tipo de documentos en ingles, español e italiano. Servicio de traduccion presencial"
keywords: "traduccion, ingles, italiano, español, inteprete público"
skills: "Traductor Oficial - Intérprete Público"
meta_author: Matteo Maria

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: 

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Maria Matteo © 2020 -- Tema original de <a href="https://startbootstrap.com/">starbootstrap.com</a>
  location: Ubicación
  social: Around the Web

# Postal address (add as many lines as necessary)
address:
  - Linea 1 de dirección
  - Linea 2 de dirección

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
