# Site settings
title: Maria Teresa Matteo Cassino
short_title: María Matteo

url: https://mariate25.github.io/Traducciones/
description: "Traducciones de todo tipo de documentos en inglés, español e italiano. Servicio de traduccion presencial"
keywords: "traduccion, ingles, italiano, español, inteprete presencial"
skills: "Intérprete Trilingüe - Redactora - Ingeniero - Pianista"
meta_author: Maria Teresa Matteo Cassino

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: 

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Maria Matteo © 2019 -- Tema original de <a href="https://startbootstrap.com/">starbootstrap.com</a>
  location: Venezuela - USA

# Postal address (add as many lines as necessary)
address:
   - Calle 31 entre Avenidas 25 y 26
   - Edificio "Cassino" Apartamento #2
   - Acarigua - Estado Portuguesa
   - VENEZUELA 3301

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
